//
//  ZADeviceId.m
//  ZhugeioAnanlytics
//
//  Created by Good_Morning_ on 2021/5/12.
//

/**
 * 先从 keychain 获取 zaid
 * 如果获取不到 生成新的 zaid 存到 keychain
 * return zaid
 */

#import "ZADeviceId.h"
#import "ZGLog.h"

@implementation ZADeviceId

+ (NSString *)getZADeviceId {
    // App-install scoped identifier. It is generated by the SDK and never derived from the device.
    return [self idFromUserDefaults];
}


+ (NSString *)idFromUserDefaults {
    static NSString * const kDeviceIdKey = @"zgid_uuid";
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    NSString *uuid = [defaults stringForKey:kDeviceIdKey];

    if (!uuid) {
        uuid = [[NSUUID UUID] UUIDString];
        [defaults setObject:uuid forKey:kDeviceIdKey];
    }
    return uuid;
}


@end
